Vagrant.configure("2") do |config|
  nodes = [
    { :hostname => "master.bminfotrade.com", :ip => "192.168.56.10", :script => "master.sh" },
    { :hostname => "worker1.com", :ip => "192.168.56.11", :script => "worker1.sh" },
    { :hostname => "worker2.com", :ip => "192.168.56.12", :script => "worker2.sh" }
  ]

  nodes.each do |node|
    config.vm.define node[:hostname] do |node_config|
      node_config.vm.box = "ubuntu/bionic64"
      node_config.vm.hostname = node[:hostname]
      node_config.vm.network "private_network", ip: node[:ip]
      node_config.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 2
      end
      node_config.vm.provision "shell", path: "setup-scripts/#{node[:script]}"
    end
  end
end
